module.exports = {
  ROLES: {
    CUSTOMER: 'CUSTOMER',
    VENDOR: 'VENDOR',
    ADMIN: 'ADMIN',
    STAFF: 'STAFF'
  },
  VENDOR_STATUS: {
    PENDING: 'PENDING',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    SUSPENDED: 'SUSPENDED'
  },
  ORDER_STATUS: {
    PENDING: 'PENDING',
    ACCEPTED: 'ACCEPTED',
    PREPARING: 'PREPARING',
    READY: 'READY',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
    REJECTED: 'REJECTED'
  },
  PAYMENT_STATUS: {
    PENDING: 'PENDING',
    PAID: 'PAID',
    FAILED: 'FAILED',
    REFUNDED: 'REFUNDED',
    PARTIALLY_REFUNDED: 'PARTIALLY_REFUNDED'
  },
  PAYMENT_METHODS: {
    ONLINE_RAZORPAY: 'ONLINE_RAZORPAY',
    CASH: 'CASH'
  },
  ORDER_TYPES: {
    PICKUP: 'PICKUP',
    DINE_IN: 'DINE_IN',
    DELIVERY: 'DELIVERY'
  }
};
